trigger:  
 branches:
  include:
    - feature/*
    - main

pool: Agent_1
steps:
- task: TerraformInstaller@1
  displayName: terraforminstall
  inputs:
    terraformVersion: 'latest'
- task: PowerShell@2
  displayName: azlogin
  inputs:
    targetType: 'inline'
    script: 'az login'
- task: TerraformTask@5
  displayName: terraforminit
  inputs:
    provider: 'azurerm'
    command: 'init'
    backendServiceArm: 'wif-prafulla'
    backendAzureRmResourceGroupName: 'rg-pipline'
    backendAzureRmStorageAccountName: 'stg22pipeline'
    backendAzureRmContainerName: 'containerpipeline22'
    backendAzureRmKey: 'key.tfstate'
- task: TerraformTask@5
  displayName: terraformplan
  inputs:
    provider: 'azurerm'
    command: 'plan'
    environmentServiceNameAzureRM: 'wif-prafulla'
- task: TerraformTask@5
  displayName: terraforminit
  inputs:
    provider: 'azurerm'
    command: 'init'
    backendServiceArm: 'wif-prafulla'
    backendAzureRmResourceGroupName: 'rg-pipline'
    backendAzureRmStorageAccountName: 'stg22pipeline'
    backendAzureRmContainerName: 'containerpipeline22'
    backendAzureRmKey: 'key.tfstate'
- task: TerraformTask@5
  displayName: terraformapply
  inputs:
    provider: 'azurerm'
    command: 'apply'
    environmentServiceNameAzureRM: 'wif-prafulla'
