trigger:  
 branches:
  include:
    - feature/*
    - main

pool: Agent_1
steps:
- task: TerraformInstaller@1
  displayName: terraforminstall
  inputs:
    terraformVersion: 'latest'
- task: TerraformTask@5
  displayName: terraforminit
  inputs:
    provider: 'azurerm'
    command: 'init'
    backendServiceArm: 'wif-prafulla'
    backendAzureRmResourceGroupName: 'rg-pipline'
    backendAzureRmStorageAccountName: 'stg22pipeline'
    backendAzureRmContainerName: 'containerpipeline22'
    backendAzureRmKey: 'key.tfstate'
- task: TerraformTask@5
  displayName: terraformplan
  inputs:
    provider: 'azurerm'
    command: 'plan'
    environmentServiceNameAzureRM: 'wif-prafulla'

- task: ManualValidation@1
  inputs:
    notifyUsers: 'prafullakumar4321@gmail.com'
    approvers: 'prafullakumar4321@gmail.com'
- task: TerraformTask@5
  displayName: terraforminit
  inputs:
    provider: 'azurerm'
    command: 'init'
    backendServiceArm: 'wif-prafulla'
    backendAzureRmResourceGroupName: 'rg-pipline'
    backendAzureRmStorageAccountName: 'stg22pipeline'
    backendAzureRmContainerName: 'containerpipeline22'
    backendAzureRmKey: 'key.tfstate'
- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'apply'
    environmentServiceNameAzureRM: 'wif-prafulla'